class ATM:
    def __init__(self):
        self.balance = 0

    def display_menu(self):
        print("\nATM Menu:")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Exit")

    def check_balance(self):
        print(f"Balance: {self.balance}")

    def deposit_money(self):
        amount = float(input("Enter amount to deposit: "))
        self.balance += amount
        print("Deposited")

    def withdraw_money(self):
        amount = float(input("Enter amount to withdraw: "))
        if amount <= self.balance:
            self.balance -= amount
            print("Withdrawn")
        else:
            print("Insufficient balance")

    def run(self):
        while True:
            self.display_menu()
            choice = input("Choose an option (1-4): ")
            if choice == "1":
                self.check_balance()
            elif choice == "2":
                self.deposit_money()
            elif choice == "3":
                self.withdraw_money()
            elif choice == "4":
                print("Goodbye!")
                break
            else:
                print("Invalid choice")

atm = ATM()
atm.run()
